cd crates/erg_proc_macros
cargo publish
cd ../erg_common
cargo publish
cd ../erg_parser
cargo publish
cd ../erg_compiler
cargo publish
cd ../erg_linter
cargo publish
cd ../els
cargo publish
cd ../../
cargo publish
echo done
