name: Docs

on:
  push:
    branches: [main]
    paths:
      - "doc/**"
      - "**.md"

jobs:
  automatic-update:
    if: github.repository_owner == 'erg-lang'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install tqdm
      - uses: erg-lang/setup-erg@v4.1
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: update summary
        run: |
          python scripts/sync_to_summary.py

          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic update \`SUMMARY.md\`"
      - name: update translation_status
        run: |
          erg --version
          erg scripts/sync_to_translation_status.er

          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic update \`translation_status\`"
      - run: |
          git push
